version: '3.8'

name: 'efrei-graphql-db'

services:
  postgres:
    image: postgres:latest
    # env_file:
    #   - ./env
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
